name: flutter_reactive_ble_example
description: Demonstrates how to use the flutter_reactive_ble plugin.
version: 5.0.2
publish_to: "none"

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^1.0.4
  functional_data: ^1.0.0
  intl: ^0.17.0
  provider: ^6.0.1
  flex_color_scheme: ^4.1.1
  signal_strength_indicator: ^0.4.1
  cupertino_radio_choice: ^1.0.2
  fl_chart: ^0.55.1
  permission_handler: ^9.0.2
  csv: ^5.0.1
  sqflite: ^2.0.2
  path_provider: ^2.0.11
  external_path: any
  share_plus: ^4.1.0
dev_dependencies:
  build_runner: ^2.1.4
  dependency_validator: ^3.1.0
  flutter_test:
    sdk: flutter
  functional_data_generator: ^1.1.2

dependency_overrides:
  flutter_reactive_ble:
    path: ../packages/flutter_reactive_ble
  reactive_ble_mobile:
    path: ../packages/reactive_ble_mobile
  reactive_ble_platform_interface:
    path: ../packages/reactive_ble_platform_interface

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/data/
